language: true

before_install:
  - chmod +x ./build/testAssignment2.sh
  - chmod +x .api

install: true

before_script:
  - export AUTHOR_NAME=$(curl -H "Authorization: token ${TOKEN}" -X GET "https://api.github.com/repos/${TRAVIS_REPO_SLUG}/pulls/${TRAVIS_PULL_REQUEST}" | jq -r '.user.login')
  - echo $AUTHOR_NAME
  
script:
  - ./build/testAssignment2.sh > err
  
after_success:
  - ./.api true
  
after_failure:
  - ./.api false
  
