sudo: required
dist: trusty

language: true

before_install:
  - chmod +x ./build/testAssignment2.sh
  - chmod +x .api

install: true

before_script:
  - touch json
  - touch name
  - curl -H "Authorization: token ${TOKEN}" -X GET "https://api.github.com/repos/${TRAVIS_REPO_SLUG}/pulls/${TRAVIS_PULL_REQUEST}" > json
  - cat json | jq -r '.user.login' > name
  - export AUTHOR_NAME=$(cat name)
  
script:
  - ./build/testAssignment2.sh > err
  
after_success:
  - ./.api true
  
after_failure:
  - ./.api false
  
