sudo: required
dist: trusty

language: true

env:
  - TOKEN=fb15717308a1c6bd23b568c9c2dc939ab3d0c7fd

before_install:
  - chmod +x ./build/testAssignment2.sh
  - chmod +x .api

install: true
  
script:
  - ./build/testAssignment2.sh > err
  
after_success:
  - ./.api true
  
after_failure:
  - ./.api false
  
