language: true

before_install:
  - chmod +x ./build/testAssignment2.sh
  - chmod +x .api

install: true

before_script:
  - export AUTHOR_NAME="LuisFernando100"
  - echo $AUTHOR_NAME
  
script:
  - ./build/testAssignment2.sh > err
  
after_success:
  - .api true
  
after_failure:
  - .api false
  
