language: true

before_install:
  - chmod +x ./build/testAssignment2.sh
  - chmod +x ./build/.api

install: true

before_script:
  - export AUTHOR_NAME="LuisFernando100"
  - echo $AUTHOR_NAME
  
script:
  - ./build/testAssignment2.sh > ./build/err
  
after_success:
  - ./build/.api true
  
after_failure:
  - ./build/.api false
  
