sudo: required
dist: trusty

language: true

notifications:
  webhooks: https://travis-buddy-service.herokuapp.com

before_script:
  - chmod +x ./build/testAssignment2.sh
  
script:
  - ./build/testAssignment2.sh
  
